# DX 601 Week 11 Homework

## Introduction

In this homework, you will practice working with systems of linear equations and review previous weeks' material.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [1]:
import math
import sys

In [2]:
!pip install matplotlib
!pip install pandas
!pip install numpy
!pip install scipy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [3]:
!pip install scikit.learn


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Shared Data

### Vineyard Data

This data set attempts to predict yields for a small vineyard in Lake Erie in 1991 based on the yields in the previous years.
Each row of the data set represents the yields of a row of the vineyard.
See https://github.com/EpistasisLab/pmlb/blob/master/datasets/192_vineyard/metadata.yaml for more information.

In [5]:
vineyard = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/192_vineyard/192_vineyard.tsv.gz", sep="\t")
vineyard.head()

,lugs_1989,lugs_1990,target
0,1.0,5.0,9.5
1,3.0,8.0,17.5
2,3.0,11.0,18.0
3,3.0,9.0,20.0
4,5.0,9.5,20.5


In [6]:
vineyard_inputs = vineyard[["lugs_1989", "lugs_1990"]]
vineyard_inputs.head()

,lugs_1989,lugs_1990
0,1.0,5.0
1,3.0,8.0
2,3.0,11.0
3,3.0,9.0
4,5.0,9.5


In [7]:
vineyard_target = vineyard["target"]

## Problems

### Problem 1

Set `p1` to the value of $x$ after solving the following system of linear equations.

\begin{array}{rcl}
3x & = & 4.2 \\
\end{array}


In [8]:
# YOUR CHANGES HERE

p1 = 1.4

In [9]:
p1

1.4

### Problem 2

Set `p2` to be a tuple of `(x, y)` where $x$ and $y$ are the solution to the following system of linear equations.

\begin{array}{rcl}
3x + 2y & = & 8.6 \\
2x + 5y & = & 13.8 \\
\end{array}


Hint: Just do this by hand.

In [10]:
# YOUR CHANGES HERE

p2 = (1.4, 2.2)
a = np.array([[3,2],[2,5]])
b = np.array([8.6,13.8])
x = np.linalg.solve(a,b)
print(x)

[1.4 2.2]


In [11]:
p2

(1.4, 2.2)

### Problem 3

Set `p3` to be the x intercept of the following equation.

\begin{array}{rcl}
4x + 2y + 3z & = & 12 \\
\end{array}

In [12]:
# YOUR CHANGES HERE

p3 = 3

In [13]:
p3

3

### Problem 4

Set `p4` to be the sum of the 5 axis intercepts of the following equation.

\begin{array}{rcl}
9a + 4b + 27c + 6d + 3e & = & 36 \\
\end{array}

In [14]:
b = np.array([[9, 4, 27, 6, 3]])
a = np.array([[36]])
p4a = np.linalg.solve(a, b)
p4 = np.sum(p4a)
print(p4)

1.3611111111111112


### Problem 5

Set `p5` to the augmented matrix of the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 13z = 10 \\
7x + 2y - 13z = 23 \\
\end{array}

In [15]:
# YOUR CHANGES HERE

p5 = np.array([[3, 2, 13, 10], [7, 2, -13, 23]])

In [16]:
p5

array([[  3,   2,  13,  10],
       [  7,   2, -13,  23]])

### Problem 6

Set `p6` to the rank of the following system of linear equations?

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

In [17]:
# YOUR CHANGES HERE

p6 = 3

In [18]:
p6

3

### Problem 7

Consider the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

This system could be rewritten as
\begin{array}{rcl}
\mathbf{A}
\begin{bmatrix}
x \\ y \\ z \\
\end{bmatrix}
& = &
\begin{bmatrix}
3 \\ 5 \\ 20 \\
\end{bmatrix}
\end{array}

Set `p7` to $\mathbf{A}$.

In [19]:
# YOUR CHANGES HERE

p7 = np.array([[3, 2, 0], [2, 3, 1], [5, 5, 5]])

In [20]:
p7

array([[3, 2, 0],
       [2, 3, 1],
       [5, 5, 5]])

### Problem 8

Set `p8` to the number of free variables in the following system of linear equations.

\begin{array}{rcl}
x + 3y + 4z = 3 \\
0x + 0y + 1z = 2 \\
x + 3y + 5z = 5 \\
\end{array}

In [21]:
# YOUR CHANGES HERE

p8 = 1

In [22]:
p8

1

### Problem 9

Set `p9` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
2x + 4y + 0z = 16 \\
1x + 3y + 1z = 16 \\
3x + 0y + 0z = 6 \\
\end{array}

In [23]:
# YOUR CHANGES HERE

p9 = (2, 3, 5)

In [24]:
p9

(2, 3, 5)

### Problem 10

Set `p10` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
x + 3y + 0z = 3 \\
0x + 0y + 1z = 2 \\
\end{array}

Hint: these equations are in reduced row echelon form, so there are shortcuts to picking solutions.

In [25]:
# YOUR CHANGES HERE

p10 = (3, 0 ,2)

In [26]:
p10

(3, 0, 2)

### Problem 11

Set `p11` to be a tuple or list of the average yields in the vineyard data set for 1989, 1990, and 1991 in that order.

In [27]:
vineyard.describe()

,lugs_1989,lugs_1990,target
count,52.000000,52.000000,52.000000
mean,3.278846,9.653846,18.086538
std,1.938803,2.337961,4.394427
min,0.000000,2.500000,2.500000
25%,2.000000,8.000000,16.000000
50%,3.000000,10.000000,19.500000
75%,5.000000,11.000000,21.000000
max,8.000000,14.000000,26.000000


In [28]:
vineyard.mean()

lugs_1989     3.278846
lugs_1990     9.653846
target       18.086538
dtype: float64

In [29]:
# YOUR CHANGES HERE

p11 = vineyard.mean().tolist()

In [30]:
p11

[3.2788461538461537, 9.653846153846153, 18.08653846153846]

### Problem 12

Set `p12` to the 95th percentile of the data in `q12`.

In [31]:
# DO NOT CHANGE

q12 = np.array([3.44857705, 2.09151799, 4.98803337, 3.8649001 , 1.20265499,
       3.89903439, 3.05276698, 0.92826333, 3.20371215, 1.81124845,
       3.53150155, 2.32418747, 1.81826697, 3.50670706, 1.37181554,
       2.95770001, 3.80008758, 2.65923837, 2.83248683, 2.91306525,
       2.18314379, 2.17931002, 2.9086665 , 3.26098354, 3.24755896,
       1.01129371, 4.56540725, 3.05517241, 2.32079938, 3.39392893,
       3.3886077 , 3.38112083, 3.88523072, 3.13214221, 3.73298754,
       4.11129171, 2.74133096, 2.4825709 , 3.21885293, 4.08327916,
       2.82768517, 2.1188981 , 3.45886466, 4.20440619, 2.25038228,
       1.59150786, 2.24486543, 3.49914959, 3.72254599, 1.84068517])

In [32]:
# YOUR ANSWER HERE

p12 = np.percentile(q12, 95)

In [33]:
p12

np.float64(4.162504674)

### Problem 13

Set `p13` to the average $L_1$ loss using the average of 1989 and 1990 vineyard yields per row to predict 1991 yields per row.

In [34]:
# YOUR CHANGES HERE

p13 = np.mean(np.abs(vineyard_target - vineyard_inputs.mean(axis=1)))

In [35]:
p13

np.float64(11.620192307692308)

### Problem 14

Build a linear regression trained with `vineyard_inputs` as its input and `vineyard_target` as its target output. Set `p14` as the output of that regression with `vineyard_inputs` as its input.

In [36]:
# YOUR CHANGES HERE

p14 = sklearn.linear_model.LinearRegression().fit(vineyard_inputs, vineyard_target)

In [37]:
p14

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


### Problem 15

Given the following data, set `p15` to the weighted variance of

| Color | Shape | Score | Probability |
|---|---|---|---:|
| red | square | 3 | 0.250 |
| blue | circle | 4 | 0.125 |
| purple | line | 2 | 0.125 |
| purple | diamond | 5 | 0.25 |
| blue | triangle | 3 | 0.25 |

In [38]:
# YOUR CHANGES HERE
p15a = pd.DataFrame({'score':[3, 4,2,5,3], 'Probability': [0.250, 0.125, 0.125, 0.25,0.25]})
p15b = np.average(p15a['score'], weights = p15a['Probability'])
p15 = np.average((p15a['score'] - p15b**2), weights =p15a['Probability'])


In [39]:
p15

np.float64(-8.75)

### Problem 16

Set `p16` to be the correlation between the 1989 and 1990 yields in the vineyard data set.

In [40]:
# YOUR CHANGES HERE

p16 = vineyard['lugs_1989'].corr(vineyard['lugs_1990'])

In [41]:
p16

np.float64(0.7224792530209387)

### Problem 17

Compute the sample mean and variance of the 1990 vineyard yields.
Assuming that the yields follow a normal distribution with your computed parameters, what would the one-sided p-value of a yield of 13 lugs be?

Hint: use the [SciPy stats module](https://docs.scipy.org/doc/scipy/reference/stats.html) to calculate the p-values from the distribution.

In [69]:

from scipy import stats

y1990 = vineyard['lugs_1990']

mean_1990 = np.mean(y1990)
var_1990 = np.var(y1990, ddof=1)
std_1990 = np.sqrt(var_1990)



In [70]:
# YOUR CHANGES HERE

p17 = stats.norm.sf(13, loc=mean_1990, scale=std_1990)

In [71]:
p17

np.float64(0.07618255849601965)

### Problem 18

Set `p18` to be the $2 \times 3$ matrix full of question marks below, filled in with the following information.
1. Each serving of noodles requires 1/2 cup of flour.
2. Each serving of noodles requires 1/8 cup of water.
3. Noodles do not need sugar.
4. Each serving of cake requires 1/4 cup of flour.
5. Each serving of cake requires 1/4 cup of sugar.
6. Cake does not need water.

\begin{array}{rcl}
\begin{bmatrix}
\text{servings of noodles} & \text{pieces of cake} \\
\end{bmatrix}
\begin{bmatrix}
\text{??} & \text{??} & \text{??} \\
\text{??} & \text{??} & \text{??} \\
\end{bmatrix}
& = &
\begin{bmatrix}
\text{flour needed} & \text{sugar needed} & \text{water needed} \\
\end{bmatrix}
\end{array}

In [75]:
# YOUR CHANGES HERE

p18 = np.array([[0.5, 1/8, 0], [0.25, 0, 0.25]])

In [76]:
p18

array([[0.5  , 0.125, 0.   ],
       [0.25 , 0.   , 0.25 ]])

### Problem 19

Set `p19` to be the cosine similarity of the vectors `x19` and `y19`.


In [46]:
# DO NOT CHANGE

x19 = [0.4, 0.2, -0.5]
x19

[0.4, 0.2, -0.5]

In [47]:
# DO NOT CHANGE

y19 = [-0.3, -0.2, 0.4]
y19

[-0.3, -0.2, 0.4]

In [48]:
# YOUR CHANGES HERE

p19 = p19 = np.dot(x19, y19) / (np.linalg.norm(x19) * np.linalg.norm(y19))

In [49]:
p19

np.float64(-0.9965457582448795)

### Problem 20

Set `p20` to the reduced row echelon form of `q20`.


In [56]:
!pip install sympy 


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [57]:
import sympy as sp

In [58]:
# DO NOT CHANGE

q20 = np.array([[2., 5., -3., 2.0],
                [-2, 1, 3, -2],
                [ 4.,  1.,  0., 16.]])

In [59]:
# YOUR CHANGES HERE

p20 = sp.Matrix(q20).rref()

In [60]:
p20

(Matrix([
 [1, 0, 0, 4.0],
 [0, 1, 0,   0],
 [0, 0, 1, 2.0]]),
 (0, 1, 2))

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR CHANGES HERE